name: fluttium_cli
description: The CLI for Fluttium, a user flow testing framework for Flutter
homepage: https://fluttium.dev
repository: https://github.com/wolfenrain/fluttium
version: 0.1.0-dev.8

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  collection: ^1.16.0
  fluttium_flow: ^0.1.0-dev.2
  fluttium_runner: ^0.1.0-dev.4
  mason: ^0.1.0-dev.34
  meta: ^1.8.0
  path: ^1.8.2
  process: ^4.2.4
  pub_updater: ^0.2.1
  watcher: ^1.0.1
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

executables:
  fluttium: