name: fluttium
description: The core package for the Fluttium user flow testing framework
homepage: https://fluttium.dev
repository: https://github.com/wolfenrain/fluttium
version: 0.1.0-dev.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  clock: ^1.1.1
  flutter:
    sdk: flutter
  fluttium_flow: ^0.1.0-dev.2

dev_dependencies:
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
