name: fluttium_flow
description: The flow definitions of the Fluttium UI testing framework.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
dependencies:
  yaml: ^3.1.1
